# Generated by Django 2.2.19 on 2023-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='teg',
        ),
        migrations.AddField(
            model_name='posts',
            name='descriptions',
            field=models.TextField(default=True),
        ),
    ]
